# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:9.9.0

    working_directory: ~/repo

    steps:
      - checkout

      # 恢复依赖缓存
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      # 安装依赖
      - run: sudo npm install -g vuepress@latest
      - run: npm install
      
      # 部署到 GitHub Pages
      - run: git config --global user.email "jacknic@qq.com"
      - run: git config --global user.name "Jacknic"
      - run: ./deploy.sh

      # 缓存依赖
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}